studio-4383054041:~/studio{main}$ git status On branch main nothing to commit, working tree clean studio-4383054041:~/studio{main}$ git log commit 83dd854720b12c2107a9a95788592a44fb5f487c (HEAD -> main) Author: Macbrian Maera <macb1738@gmail.com> Date:   Wed May 21 20:05:19 2025 +0000
    I see this error with the app, reported by NextJS, please fix it. The error is reported as HTML but presented visually to the user).

    A > before the line number in the error source usually indicates the line of interest:

    > Cannot find module './548.js'
    > Require stack:
    > - /home/user/studio/.next/server/webpack-runtime.js
    > - /home/user/studio/.next/server/pages/_document.js
    > - /home/user/studio/node_modules/next/dist/server/require.js
    > - /home/user/studio/node_modules/next/dist/server/load-components.js
    > - /home/user/studio/node_modules/next/dist/build/utils.js
    > - /home/user/studio/node_modules/next/dist/build/swc/options.js
    > - /home/user/studio/node_modules/next/dist/build/swc/index.js
    > - /home/user/studio/node_modules/next/dist/build/next-config-ts/transpile-config
.js
    > - /home/user/studio/node_modules/next/dist/server/config.js
    > - /home/user/studio/node_modules/next/dist/server/next.js
    > - /home/user/studio/node_modules/next/dist/server/lib/start-server.js

commit b108f0d5ea6b42d90b0500c9e944f617e047033b
Author: Macbrian Maera <macb1738@gmail.com>
Date:   Wed May 21 19:54:37 2025 +0000

    remove all logins portal and their respective queries. i dont want any user to hav
e to login or create an account

commit 0ad47988217159f5c8732b26fdfdc9e4b354e195
Author: Macbrian Maera <macb1738@gmail.com>
Date:   Wed May 21 19:48:36 2025 +0000

    [schema] invalid Data Connect schema: schema/academics.gql:8: Undefined directive
pk.

    Error: Unable to generate your Data Connect SDKs (exit code 1): E0521 19:35:03.546
107   40688 cmd.go:45] Failed to generate SDKs:
    [schema] invalid Data Connect schema: schema/academics.gql:8: Undefined directive
pk.