✔  Deploy complete!
Project Console: https://console.firebase.google.com/project/sibiah-star-connect/overview
Hosting URL: https://sibiah-star-connect.web.app
studio-4383054041:~/studio{main}$ npm run build

> nextn@0.1.0 build
> next build

   ▲ Next.js 15.2.3
   - Environments: .env.local, .env

   Creating an optimized production build ...
 ⚠ Compiled with warnings

./node_modules/@opentelemetry/sdk-node/build/src/TracerProviderWithEnvExporter.js
Module not found: Can't resolve '@opentelemetry/exporter-jaeger' in '/home/user/studio/node_modules/@opentelemetry/sdk-node/build/src'

Import trace for requested module:
./node_modules/@opentelemetry/sdk-node/build/src/TracerProviderWithEnvExporter.js
./node_modules/@opentelemetry/sdk-node/build/src/sdk.js
./node_modules/@opentelemetry/sdk-node/build/src/index.js
./node_modules/@genkit-ai/core/lib/tracing.js
./node_modules/genkit/lib/tracing.js
./node_modules/@genkit-ai/googleai/lib/gemini.js
./node_modules/@genkit-ai/googleai/lib/index.mjs
./src/ai/genkit.ts
./src/ai/flows/admission-question-generator.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/admission-question-generator.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/admission-question-generator.ts

./node_modules/handlebars/lib/index.js
require.extensions is not supported by webpack. Use a loader instead.

Import trace for requested module:
./node_modules/handlebars/lib/index.js
./node_modules/dotprompt/dist/index.js
./node_modules/@genkit-ai/core/lib/registry.js
./node_modules/genkit/lib/registry.js
./node_modules/genkit/lib/genkit.js
./node_modules/genkit/lib/index.mjs
./src/ai/flows/admission-question-generator.ts

 ✓ Compiled successfully
   Linting and checking validity of types  .Failed to compile.

./src/app/parent-portal/register/page.tsx:50:3
Type error: Cannot find name 'useEffect'.

  48 |   });
  49 |
> 50 |   useEffect(() => {
     |   ^
  51 |     if (!initialLoading && user) {
  52 |       router.push('/parent-portal'); // Redirect if already logged in
  53 |     }
Next.js build worker exited with code: 1 and signal: null