✔  database: required API firebasedatabase.googleapis.com is enabled
Firebase Realtime Database Security Rules allow you to define how your data should be
structured and when your data can be read from and written to.

✔ File database.rules.json already exists. Do you want to overwrite it with the Realtime Database Security Rules for sibiah-star-connect-default-rtdb from
the Firebase console? No
Skipping overwrite of Realtime Database Security Rules.
The security rules defined in database.rules.json will be published when you run firebase deploy.

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...

✔  Firebase initialization complete!
studio-4383054041:~/studio{main}$ firebase deploy

=== Deploying to 'sibiah-star-connect'...

i  deploying database, storage, firestore, functions, hosting, remoteconfig, extensions, dataconnect
Running command: npm --prefix "$RESOURCE_DIR" run build
npm error Missing script: "build"
npm error
npm error To see a list of scripts, run:
npm error   npm run
npm error A complete log of this run can be found in: /home/.npm/_logs/2025-05-15T17_06_25_567Z-debug-0.log

Error: functions predeploy error: Command terminated with non-zero exit code 1
studio-4383054041:~/studio{main}$