studio-4383054041:~/studio{master}$ firebase deploy
=== Deploying to 'sibiah-star-connect'...

i  deploying database, storage, firestore, functions, hosting, remoteconfig, extensions, dataconnect
Running command: npm --prefix "$RESOURCE_DIR" run lint

> lint
> eslint --ext .js,.ts .

/home/user/studio/functions/index.js
  0:0  error  Parsing error: ESLint was configured to run on `<tsconfigRootDir>/index.js` using `parserOptions.project`:
- <tsconfigRootDir>/tsconfig.json
- <tsconfigRootDir>/tsconfig.dev.json
However, none of those TSConfigs include this file. Either:
- Change ESLint's list of included files to not include this file
- Change one of those TSConfigs to include this file
- Create a new TSConfig that includes this file and include it in your parserOptions.project
See the typescript-eslint docs for more info: https://typescript-eslint.io/linting/troubleshooting#i-get-errors-telling-me-eslint-was-configured-to-run--however-that-tsconfig-does-not--none-of-those-tsconfigs-include-this-file

/home/user/studio/functions/src/genkit-sample.ts
   3:24  warning  '@genkit-ai/vertexai' imported multiple times         import/no-duplicates
   7:29  warning  '@genkit-ai/vertexai' imported multiple times         import/no-duplicates
   9:1   error    This line has a length of 102. Maximum allowed is 80  max-len
  10:1   error    This line has a length of 90. Maximum allowed is 80   max-len
  11:1   error    This line has a length of 89. Maximum allowed is 80   max-len
  13:9   error    There should be no space after '{'                    object-curly-spacing
  13:24  warning  'hasClaim' is defined but never used                  @typescript-eslint/no-unused-vars
  13:32  error    There should be no space before '}'                   object-curly-spacing
  15:1   error    This line has a length of 102. Maximum allowed is 80  max-len
  16:1   error    This line has a length of 100. Maximum allowed is 80  max-len
  18:9   error    There should be no space after '{'                    object-curly-spacing
  18:22  error    There should be no space before '}'                   object-curly-spacing
  32:1   error    Expected indentation of 2 spaces but found 4          indent
  33:1   error    Expected indentation of 2 spaces but found 4          indent
  34:1   error    Expected indentation of 2 spaces but found 4          indent
  35:1   error    Expected indentation of 2 spaces but found 4          indent
  36:1   error    Expected indentation of 0 spaces but found 2          indent
  36:23  error    There should be no space after '{'                    object-curly-spacing
  36:33  error    There should be no space before '}'                   object-curly-spacing
  37:1   error    Expected indentation of 2 spaces but found 4          indent
  38:1   error    Expected indentation of 2 spaces but found 4          indent
  40:1   error    Expected indentation of 2 spaces but found 4          indent
  40:12  error    There should be no space after '{'                    object-curly-spacing
  40:29  error    There should be no space before '}'                   object-curly-spacing
  41:1   error    Expected indentation of 4 spaces but found 6          indent
  42:1   error    Expected indentation of 4 spaces but found 6          indent
  43:1   error    Expected indentation of 4 spaces but found 6          indent
  44:1   error    Expected indentation of 6 spaces but found 8          indent
  45:1   error    Expected indentation of 4 spaces but found 6          indent
  46:1   error    Expected indentation of 2 spaces but found 4          indent
  48:1   error    Expected indentation of 2 spaces but found 4          indent
  49:1   error    Expected indentation of 4 spaces but found 6          indent
  50:1   error    Expected indentation of 2 spaces but found 4          indent
  52:1   error    Expected indentation of 2 spaces but found 4          indent
  53:1   error    Expected indentation of 2 spaces but found 4          indent
  54:1   error    Expected indentation of 2 spaces but found 4          indent
  55:1   error    Expected indentation of 2 spaces but found 4          indent
  56:1   error    Expected indentation of 2 spaces but found 4          indent
  57:1   error    Expected indentation of 0 spaces but found 2          indent
  61:1   error    This line has a length of 87. Maximum allowed is 80   max-len
  65:1   error    This line has a length of 98. Maximum allowed is 80   max-len
  66:1   error    This line has a length of 97. Maximum allowed is 80   max-len

/home/user/studio/functions/src/index.ts
  10:9   warning  'onRequest' is defined but never used  @typescript-eslint/no-unused-vars
  11:13  warning  'logger' is defined but never used     @typescript-eslint/no-unused-vars

✖ 45 problems (40 errors, 5 warnings)
  31 errors and 0 warnings potentially fixable with the `--fix` option.

Error: functions predeploy error: Command terminated with non-zero exit code 1
studio-4383054041:~/studio{master}$