src/index.ts:10:1 - error TS6133: 'onRequest' is declared but its value is never read.
10 import {onRequest} from "firebase-functions/v2/https";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:11:1 - error TS6133: 'logger' is declared but its value is never read.

11 import * as logger from "firebase-functions/logger";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: src/index.ts:10

Error: functions predeploy error: Command terminated with non-zero exit code 2
studio-4383054041:~/studio{main}$