######## #### ########  ######## ########     ###     ######  ########      ##        ##  ##     ## ##       ##     ##  ##   ##  ##       ##      ######    ##  ########  ######   ########  #########  ######  ######      ##        ##  ##    ##  ##       ##     ## ##     ##       ## ##      ##       #### ##     ## ######## ########  ##     ##  ######  ########
You're about to initialize a Firebase project in this directory:

  /home/user/studio

Before we get started, keep in mind:

  * You are initializing within an existing Firebase project directory

=== Project Setup

First, let's associate this project directory with a Firebase project.
You can create multiple project aliases by running firebase use --add,
but for now we'll just set up a default project.

i  Using project sibiah-star-connect (Sibiah Star Connect)

=== Dataconnect Setup
i  dataconnect: ensuring required API firebasedataconnect.googleapis.com is enabled...
✔  dataconnect: required API firebasedataconnect.googleapis.com is enabled
i  dataconnect: ensuring required API sqladmin.googleapis.com is enabled...
✔  dataconnect: required API sqladmin.googleapis.com is enabled
i  dataconnect: ensuring required API compute.googleapis.com is enabled...
✔  dataconnect: required API compute.googleapis.com is enabled
✔ Your project already has existing services. Which would you like to set up local files for? us-central1/studio
i  dataconnect/dataconnect.yaml is unchanged
i  dataconnect/schema/schema.gql is unchanged
✔ File dataconnect/connector/connector.yaml already exists. Overwrite? Yes
✔  Wrote dataconnect/connector/connector.yaml
i  dataconnect/connector/mutations.gql is unchanged
i  dataconnect/connector/queries.gql is unchanged
✔  Detected WEB app in directory /home/user/studio
✔ Which connector do you want set up a generated SDK for? studio/default
i  Detected react app. Enabling react generated SDKs.
✔ Which frameworks would you like to generate SDKs for? Press Space to select features, then Enter to confirm your choices. react
i  Writing your new SDK configuration to /home/user/studio/dataconnect/connector/connector.yaml
✔ File dataconnect/connector/connector.yaml already exists. Overwrite? Yes
✔  Wrote dataconnect/connector/connector.yaml
[winston] Unknown logger level: DEBUG
I0521 19:05:39.736286   33570 codegen.go:82] [connector "default" javascriptSdk] Generating sources into "/home/user/studio/dataconnect-generated/js/default-connector"
I0521 19:05:39.747470   33570 generate.go:40] Generated all sources. Writing them to disk...
I0521 19:05:39.751995   33570 collector.go:107] connector "default" javascriptSdk wrote into "/home/user/studio/dataconnect-generated/js/default-connector"
Generated sources: package.json [860B] README.md [2774B] react/index.d.ts [228B] react/README.md [5357B] index.d.ts [246B] esm/index.esm.js [109B] index.cjs.js [144B] react/index.cjs.js [0B] react/esm/index.esm.js [0B] esm/package.json [17B] react/package.json [468B] react/esm/package.json [17B]
I0521 19:05:39.796729   33570 installsdk.go:49] Package @firebasegen/default-connector is already installed. Skipping installation

i  Generated SDK code for default
i  Visit https://firebase.google.com/docs/data-connect/web-sdk#react for more information on how to set up React Generated SDKs for Firebase Data Connect
✔  If you'd like to add more generated SDKs to your app your later, run firebase init dataconnect:sdk again

i  Writing configuration info to firebase.json...
i  Writing project information to .firebaserc...
studio-4383054041:~/studio{main}$
studio-4383054041:~/studio{main}$
studio-4383054041:~/studio{main}$ firebase dataconnect:sdk:generate
[winston] Unknown logger level: DEBUG
E0521 19:30:18.899317   39276 cmd.go:45] Failed to generate SDKs:
[schema] invalid Data Connect schema: schema/academics.gql:33: Expected Name, found @

Error: Unable to generate your Data Connect SDKs (exit code 1): E0521 19:30:18.899317   39276 cmd.go:45] Failed to generate SDKs:
[schema] invalid Data Connect schema: schema/academics.gql:33: Expected Name, found @