studio-4383054041:~/studio{main}$ npm install -g firebase-tools
added 1 package, and changed 694 packages in 43s

78 packages are looking for funding
  run `npm fund` for details
studio-4383054041:~/studio{main}$ firebase deploy

=== Deploying to 'sibiah-star-connect'...

i  deploying database, storage, firestore, functions, hosting, remoteconfig, extensions, dataconnect
Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

src/genkit-sample.ts:13:24 - error TS6133: 'hasClaim' is declared but its value is never read.

13 import { onCallGenkit, hasClaim } from "firebase-functions/https";
                          ~~~~~~~~

Found 1 error in src/genkit-sample.ts:13

Error: functions predeploy error: Command terminated with non-zero exit code 2
studio-4383054041:~/studio{main}$ firebase deploy

=== Deploying to 'sibiah-star-connect'...

i  deploying database, storage, firestore, functions, hosting, remoteconfig, extensions, dataconnect
Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

src/index.ts:10:1 - error TS6133: 'onRequest' is declared but its value is never read.

10 import {onRequest} from "firebase-functions/v2/https";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:11:1 - error TS6133: 'logger' is declared but its value is never read.

11 import * as logger from "firebase-functions/logger";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: src/index.ts:10

Error: functions predeploy error: Command terminated with non-zero exit code 2
studio-4383054041:~/studio{main}$ firebase deploy

=== Deploying to 'sibiah-star-connect'...

i  deploying database, storage, firestore, functions, hosting, remoteconfig, extensions, dataconnect
Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

✔  functions: Finished running predeploy script.
Running command: npm --prefix "$RESOURCE_DIR" run build

> build
> tsc

src/index.ts:10:1 - error TS6133: 'onRequest' is declared but its value is never read.

10 import {onRequest} from "firebase-functions/v2/https";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/index.ts:11:1 - error TS6133: 'logger' is declared but its value is never read.

11 import * as logger from "firebase-functions/logger";
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Found 2 errors in the same file, starting at: src/index.ts:10

Error: functions predeploy error: Command terminated with non-zero exit code 2